name: aioapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.1
  firebase_core: ^2.30.1
  firebase_database: ^10.5.3
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.1
  ollama: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
