// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvxzRFCjrpVaxDkc4TQJKaoFBUcPezgGU',
    appId: '1:506838825198:web:87fee6b015b5bbfee81bff',
    messagingSenderId: '506838825198',
    projectId: 'projectaioapp',
    authDomain: 'projectaioapp.firebaseapp.com',
    storageBucket: 'projectaioapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0CnWcbvVn4SZuj8eaAgFPqIErMCmPk2g',
    appId: '1:506838825198:android:74524d3aea8b868de81bff',
    messagingSenderId: '506838825198',
    projectId: 'projectaioapp',
    storageBucket: 'projectaioapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0AO6asEGzfD3nEUxAaNGmWcCWIuv4pXU',
    appId: '1:506838825198:ios:a90849ee3c0d2005e81bff',
    messagingSenderId: '506838825198',
    projectId: 'projectaioapp',
    storageBucket: 'projectaioapp.appspot.com',
    iosBundleId: 'com.example.aioapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0AO6asEGzfD3nEUxAaNGmWcCWIuv4pXU',
    appId: '1:506838825198:ios:5f5807ff173c0466e81bff',
    messagingSenderId: '506838825198',
    projectId: 'projectaioapp',
    storageBucket: 'projectaioapp.appspot.com',
    iosBundleId: 'com.example.aioapp.RunnerTests',
  );
}
